name: deploy node-js application

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout source
        uses: actions/checkout@v4
      - name: login to docker hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: build docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/nodejs-aws-deploy .
      - name: publish image to docker hub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/nodejs-aws-deploy:latest

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: remove nodejs-aws-deploy-container
        run: docker rm -f nodejs-aws-deploy-container
      - name: pull image from docker hub
        run: docker pull ${{ secrets.DOCKER_USERNAME }}/nodejs:latest
      - name: run docker container
        run: |
          docker run -d -p 3001:3001 \
            --name nodejs-aws-deploy-container \
            -e DB_NAME='${{ secrets.DB_NAME }}' \
            -e MONGO_URI='${{ secrets.MONGO_URI }}' \
            -e AWS_ACCESS_KEY_ID='${{ secrets.AWS_ACCESS_KEY_ID }}' \
            -e AWS_SECRET_ACCESS_KEY='${{ secrets.AWS_SECRET_ACCESS_KEY }}' \
            -e AWS_REGION='${{ secrets.AWS_REGION }}' \
            -e S3_BUCKET_NAME='${{ secrets.S3_BUCKET_NAME }}' \
            -e PORT='${{ secrets.PORT }}' \
            ${{ secrets.DOCKER_USERNAME }}/nodejs-aws-deploy